import {
  accountSchema,
  sessionSchema,
  userSchema,
  verificationSchema
} from '@better-auth/core/db';
import { getTableColumns } from 'drizzle-orm';
import { describe, expect, it } from 'vitest';

import { accounts, sessions, users, verifications } from './db/schema';

/**
 * Holds our tables to what better-auth actually requires.
 *
 * This exists because of a real miss: `issuer` was added to the account table
 * in better-auth 1.7, the schema here was generated by a CLI that resolved to
 * 1.4, and nothing noticed. Sign-in by emailed code never writes an account
 * row, so the integration tests passed while social sign-in would have failed
 * on the first attempt against a column that did not exist.
 *
 * Comparing against better-auth's own zod schemas rather than a copied list
 * means the next field it adds fails here instead of in production.
 */

const tables = [
  { name: 'user', schema: userSchema, table: users },
  { name: 'session', schema: sessionSchema, table: sessions },
  { name: 'account', schema: accountSchema, table: accounts },
  { name: 'verification', schema: verificationSchema, table: verifications }
] as const;

describe('better-auth schema conformance', () => {
  it.each(tables)(
    '$name has every field better-auth declares',
    ({ schema, table }) => {
      const required = Object.keys(schema.shape);
      const present = Object.keys(getTableColumns(table));

      expect(required.filter(field => !present.includes(field))).toEqual([]);
    }
  );

  it('scopes account identity by issuer', () => {
    // The pair is what stops two providers claiming the same identity, so both
    // halves have to exist — a unique index on `accountId` alone would reject
    // the same external id arriving from a different provider.
    const columns = getTableColumns(accounts);

    expect(columns.issuer).toBeDefined();
    expect(columns.accountId).toBeDefined();
    expect(columns.issuer.notNull).toBe(true);
  });
});
