import 'server-only';

import { generateImage, generateText, ModelMessage } from 'ai';

import { Model } from '@/types';
import { resolveAutoOption } from '@/lib/media-options';
import { StoredMedia, uploadGeneratedMedia } from '@/lib/media-upload';
import {
  FailoverProvider,
  getImageModel,
  getLanguageModel,
  runWithProviderFailover
} from '@/lib/provider';

export type InputImage = {
  data: Uint8Array | string;
  mediaType: string;
};

export type ImageGenerationResult = StoredMedia & {
  inputTokens?: number;
  outputTokens?: number;
  provider: FailoverProvider;
};

/**
 * Generate an image (optionally editing input images) with provider failover
 * and upload it to Vercel Blob. Shared by the standalone /api/images route and
 * the chat `generate_image` / `edit_image` tools.
 */
export async function generateAndStoreImage(args: {
  userId: string;
  prompt: string;
  dbModel: Model;
  candidates: FailoverProvider[];
  size?: `${number}x${number}` | string;
  aspectRatio?: `${number}:${number}`;
  inputImages?: InputImage[];
  abortSignal?: AbortSignal;
}): Promise<ImageGenerationResult> {
  const { userId, prompt, dbModel, candidates, inputImages, abortSignal } =
    args;
  // 'auto' (admin-configurable option) means: let the provider decide.
  const size = resolveAutoOption(args.size);
  const aspectRatio = resolveAutoOption(args.aspectRatio);
  const modelId = dbModel.modelId;

  const { result, provider: usedProvider } = await runWithProviderFailover(
    candidates,
    async provider => {
      let imageBase64: string;
      let imageMediaType: string;
      // Token counts for token-billed image models (e.g. gpt-image-1).
      // Undefined for per-image models — recordImageUsage falls back to
      // per-image pricing.
      let inputTokens: number | undefined;
      let outputTokens: number | undefined;

      // Gemini serves images via generateText (multi-modal); other providers
      // use the generateImage API.
      if (provider.type === 'google' && modelId.startsWith('gemini')) {
        const messages: ModelMessage[] = [
          {
            role: 'user',
            content: [
              ...(inputImages ?? []).map(image => ({
                type: 'image' as const,
                image: image.data,
                mediaType: image.mediaType
              })),
              { type: 'text' as const, text: prompt }
            ]
          }
        ];

        const genResult = await generateText({
          model: getLanguageModel(provider, modelId),
          messages,
          temperature: dbModel.apiParams?.temperature,
          topP: dbModel.apiParams?.topP,
          topK: dbModel.apiParams?.topK,
          maxOutputTokens: dbModel.apiParams?.maxOutputTokens,
          frequencyPenalty: dbModel.apiParams?.frequencyPenalty,
          presencePenalty: dbModel.apiParams?.presencePenalty,
          abortSignal,
          providerOptions: {
            [provider.type]: {
              ...provider.apiOptions,
              imageConfig: {
                ...(aspectRatio && { aspectRatio }),
                ...(size && { imageSize: size })
              }
            }
          } as any
        });

        const imageFile = genResult.files?.find(f =>
          f.mediaType.startsWith('image/')
        );
        if (!imageFile) {
          throw new Error('No image generated by the model');
        }

        imageBase64 = imageFile.base64;
        imageMediaType = imageFile.mediaType;
        inputTokens = genResult.usage?.inputTokens;
        outputTokens = genResult.usage?.outputTokens;
      } else {
        // Standard image models use generateImage API
        const standardSize = size?.includes('x')
          ? (size as `${number}x${number}`)
          : undefined;

        const { image, usage } = await generateImage({
          model: getImageModel(provider, modelId),
          prompt: inputImages?.length
            ? { text: prompt, images: inputImages.map(image => image.data) }
            : prompt,
          n: 1,
          size: standardSize,
          aspectRatio,
          abortSignal,
          ...(provider.apiOptions && {
            providerOptions: {
              [provider.type]: provider.apiOptions
            } as any
          })
        });

        imageBase64 = image.base64;
        imageMediaType = image.mediaType;
        inputTokens = usage?.inputTokens;
        outputTokens = usage?.outputTokens;
      }

      return { imageBase64, imageMediaType, inputTokens, outputTokens };
    }
  );

  const buffer = Buffer.from(result.imageBase64, 'base64');
  const ext = result.imageMediaType?.split('/')[1] || 'png';

  const stored = await uploadGeneratedMedia({
    userId,
    kind: 'generate-images',
    buffer,
    mediaType: result.imageMediaType,
    ext
  });

  return {
    ...stored,
    inputTokens: result.inputTokens,
    outputTokens: result.outputTokens,
    provider: usedProvider
  };
}
